server:
  port: 8081
dubbo:
    protocol:
        name: dubbo
        port: 20881
    application:
        name: provider-server #当前应用名字 
    registry:
        address: zookeeper://127.0.0.1:2181 #注册中心地址
    scan:
        base-packages: com.knewhow.provider.service #扫描指定包下服务